#!/usr/bin/env bash
# powerdown - powerup

if [[ $EUID != 0 ]]; then
  echo "[powerdown] must be run as root"
  exit 1
fi

source /usr/local/lib/powerdown-functions

# bus
for i in /sys/bus/{pci,spi,i2c}/devices/*/power/control; do opt $i on; done

# aspm
opt /sys/module/pcie_aspm/parameters/policy default

# usb autosuspend
opt /sys/module/usbcore/parameters/autosuspend 0
for i in /sys/bus/usb/devices/*/power/autosuspend; do opt $i 0; done
for i in /sys/bus/usb/devices/*/power/control; do opt $i on; done
for i in /sys/bus/usb/devices/*/power/level; do opt $i on; done

# cpu
for i in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do opt $i ondemand; done

# kernel write mode
opt /proc/sys/vm/laptop_mode 0
opt /proc/sys/vm/dirty_ratio 30
opt /proc/sys/vm/dirty_background_ratio 30
opt /proc/sys/vm/dirty_expire_centisecs 1500
opt /proc/sys/vm/dirty_writeback_centisecs 1500

# Disk powersave
for dev in "/dev/sd[a-z]"; do run hdparm -W 1 -S 0 -B 254 $dev; done
for dev in "/dev/sd[a-z]"; do run blockdev --setra 256 $dev; done
for i in /sys/class/scsi_host/host*/link_power_management_policy; do opt $i max_performance; done

# remount root partition relatime
run mount -o remount,relatime,commit=60 /dev/sda2
run mount -o remount,commit=60 /dev/sda3

# Sound card powersave
opt /sys/module/snd_hda_intel/parameters/power_save 0
opt /sys/module/snd_hda_intel/parameters/power_save_controller N

# enable WakeOnLan on eth0
run ethtool -s eth0 wol g

# wlan0/eth0 powersave
run iwconfig wlan0 power off

# Screen powersave
for i in /sys/class/backlight/acpi_video*/brightness; do opt $i 15; done

# Enable webcam
#load uvcvideo
#load nouveau
#load videodev

# Enable bluetooth
#load btusb
#load bluetooth

