#!/usr/bin/env bash

if [[ $EUID != 0 ]]; then
  echo "[powerdown] must be run as root"
  exit 1
fi

source /usr/local/lib/powerdown-functions

if [[ $(on_ac) -eq 1 ]]; then
  powerup
else
  powerdown
fi
