#!/bin/bash
#
# Example config file for cdm(1).
# Values set here is the default as in cdm(1).

# List of programs, commands with whitespaces should be quoted or escaped.
# If unset, all sessions in /etc/X11/Sessions are offered as choices.
binlist=(
  "~/.xinitrc wmfs2"
  "/usr/lib/systemd/systemd --user --unit=wm.target"
  "/bin/zsh --login"
  "/usr/bin/systemctl poweroff"
  "/usr/bin/systemctl reboot"
  "/usr/bin/systemctl suspend"
  "/usr/bin/systemctl hibernate"
)

# List all program display names, one-by-one matched with $binlist.
# Names with whitespaces should be quoted or escaped.
namelist=("WMFS2" "WMFS2 systemd" "Console" "Shutdown" "Reboot" "Suspend" "Hibernate")

# Type of the programs, one-by-one matched with $binlist.
# `C' for *C*onsole programs, which would be `exec'ed.
# `X' for *X* programs, which would be run with cdm-xlaunch(1).
flaglist=(X C C C C C C)

# Style for the cdm dialog, which is printed with dialog(1).
# Default to unset, causing dialog(1) to use the system wide default.
# See /usr/share/doc/cdm/themes for some nice choices.
dialogrc=/usr/share/cdm/themes/cdm

# Index of the first item in the menu.
countfrom=1

# Set default display.
display=0

# Where should the first X tty be spawned?
# special value 'keep' causes to run X in current tty
xtty="keep"

# Should cdm(1) stick to the specified display?
locktty=no

# Additional arguments to pass to X server, which is usually called as:
#   /usr/bin/X :$display $serverargs vt$((xtty+display))
serverargs='-nolisten tcp'

# Use ConsoleKit for X session?
consolekit=no

# Timeout for waiting for X session to register with ConsoleKit.
cktimeout=30

