#!/bin/sh

target="/etc/pacman.d/mirrorlist"
tmp="/tmp/mirrorlist.tmp"

# exit on error
set -e

# test if online
ping -c 1 archlinux.org > /dev/null 2>&1

reflector -a 12 -c "Czech Republic" -c "Germany" -n 10 --sort rate --save "$tmp"
mv -f "$target" "$target.old"
mv -f "$tmp" "$target"
